### ISSUE TITLE
Feedback for "Dos and Don'ts"

### ISSUE THREAD

**Issue by jung-thomas** [SAP-docs/contribution-guidelines#41]
https://help.sap.com/webcomponents/products/open-documentation-initiative/contribution-guidelines/dos-and-donts.html

> Don't ask for new features, nor for enhancements or changes to existing features.

I assume here that we mean new SAP product features or enhancements.  But new features for the documentation would be acceptable?  Because when I first read this sentence my mind was actually thinking documentation features or enhancements.  Maybe we want to clarify that.

**Comment by qmacro** [comment]
Thanks @jung-thomas - if it's not clear, it's worth an amendment. Done.

**Comment by jung-thomas** [comment]
https://people.sap.com/thomas.jung
