### ISSUE TITLE
community-id-requester workflow adds comments for all labeled PRs

### ISSUE THREAD

**Issue by je-hal** [SAP-docs/contribution-guidelines#46]
The [documentation for the workflow](https://github.com/SAP-docs/contribution-guidelines/blob/main/.github/workflows/community-id-requester.yaml#L17) says:

> it adds a comment only after the first time the label [Contribution] is added

However, the comment is added _every time_ the label is added, for example, check the following contributions of user qmacro:

https://github.com/SAP-docs/contribution-guidelines/pulls?q=is%3Apr+is%3Aclosed+author%3Aqmacro+label%3Acontribution

This leads to unnecessary comments and notifications.

**Comment by qmacro** [comment]
Thanks for highlighting. I've added a step to count the number of previously labelled objects, so we can check to ensure we only ask once. Done in #47.
