### ISSUE TITLE
Need to take SAP-docs org owners into account in disallowed checks

### ISSUE THREAD

**Issue by qmacro** [SAP-docs/contribution-guidelines#55]
This PR https://github.com/SAP-docs/btp-business-application-studio/pull/14 caused a ['disallowed content' message](https://github.com/SAP-docs/btp-business-application-studio/pull/14#issuecomment-851924400) to be generated. This is because the PR author @Shegox is not in the repo's admin team. We should extend the [membership check](https://github.com/SAP-docs/contribution-guidelines/blob/5c2311f792f68d8b1a47dac02a88bfc564490041/.github/workflows/disallowed-content-checks.yaml#L49-L60) to take into account organisation level members.

**Comment by Shegox** [comment]
As a potential solution would be replacing the whole check with check, which determines if a user has admin/write (depending on what we want) permissions to the repository via https://docs.github.com/en/rest/reference/repos#get-repository-permissions-for-a-user

**Comment by qmacro** [comment]
Thanks @shegox, this is a great suggestion, and means we only need to make one check (one API call).
