### ISSUE TITLE
Add link to READme file

### ISSUE THREAD

**Issue by cyberpinguin** [SAP-docs/contribution-guidelines#65]
There is a link missing to the guidelines on SAP Help Portal. As I'm not allowed to contribute to the readme file, somebody else needs to add this:
[SAP Help Portal](https://help.sap.com/viewer/contribution-guidelines/1.0/en-US/readme.html?q=contribution%20guidelines)

**Comment by Shegox** [comment]
I added as well a link to the repository description (GitHub metadata) to point to https://help.sap.com/viewer/contribution-guidelines/1.0/en-US. 

I would as well remove the `?q=contribution%20guidelines` from the link to not highlight stuff directly. The above url should be the link to the entry point. 

//cc @qmacro

**Comment by qmacro** [comment]
Taken care of with #64 . Thanks for the heads-up @cyberpinguin (and sorry for the tardiness!)
