### ISSUE TITLE
Feedback for "How to Provide Feedback"

### ISSUE THREAD

**Issue by hal-ey** [SAP-docs/contribution-guidelines#86]
https://help.sap.com/docs/open-documentation-initiative/contribution-guidelines/feedback.html

Hi there, 

we encountered an issue today. Although the repos in the sap-docs org are public, a customer couldn't fork the repositories. I couldn't find any hint in the documentation what setting might limit forking public repositories. Let's see if we can find out the root cause. If so, it would be good to share this information in the contribution guidelines.

This is the error we got:
<img width="767" alt="Cannot-Fork" src="https://user-images.githubusercontent.com/85878071/172609302-604221c7-d130-42fe-8d89-edf32c9a09c6.png">

**Comment by je-hal** [comment]
@SebastianWolf-SAP : Have you seen this before in your GitHub life? - Thanks!

**Comment by SebastianWolf-SAP** [comment]
No, never seen that, couldn't reproduce with my private user, also couldn't find documentation about that. More details (which repository etc.) would be helpful. 

Moreover, the customer could check with their enterprise admins if they disabled something in their [enterprise settings](https://docs.github.com/en/enterprise-cloud@latest/admin).

**Comment by je-hal** [comment]
The customer tried to create a fork or to create an issue in the following repositories:
* https://github.com/SAP-docs/btp-process-orchestration-migration-guide
* https://github.com/SAP-docs/btp-cloud-platform

The customer could neither fork the repo, nor create an issue.

I couldn't reproduce it with my private user either.

**Comment by SebastianWolf-SAP** [comment]
In this case, please ask the customer if they have special enterprise restrictions (see my previous post).

**Comment by je-hal** [comment]
It looks as if the customer had an _Enterprise Managemed User_ (EMU). The [documentation](https://docs.github.com/en/enterprise-cloud@latest/admin/identity-and-access-management/using-enterprise-managed-users-for-iam/about-enterprise-managed-users) suggests that such users cannot fork repositories of other organizations:

> Managed user accounts cannot fork repositories from outside of the enterprise or fork internal repositories. Managed user accounts can fork private repositories owned by organizations in the enterprise into other organizations owned by the enterprise, or as a fork owned by the managed user account.

I'll open a GitHub ticket to see if there is a way to add organizations outside of their enterprise org to an exclusion list, so that forking could be possible anyway.

**Comment by Shegox** [comment]
GitHub Enterprise Cloud with EMUs is intended from GitHub to pretty much have a fenced area within github.com, where nobody else has access and this users can't interact with the outside world. It is quite heavy isolated to prevent users from accidentally leaking information and from the level of isolation better comparable with an instance of GitHub Enterprise Server. 

I personally don't see that GitHub will loosen the restriction in that regard. From my perspective EMUs should use a "normal" github.com account to contribute to/interact with SAP-docs in the same way they need for any other open source project today.

**Comment by je-hal** [comment]
This is the answer from GitHub support:

> This is by design and a security feature that was frequently requested as part of the EMU design. Users who need to fork from outside of their EMU enterprise will need to create a personal GitHub account to do so.
>
> Another alternative for a one-off transfer would be to manually import the Git repository data into their EMU enterprise, but no fork relationship would be established. Multiple remotes could be configured to merge new changes locally, however.

So to allow customers with EMUs to open a PR in our repository, there is no other way than to create a personal GitHub account.
