### ISSUE TITLE
Feedback for "SAP Terminology" brokenlink http://www.sapterm.com/

### ISSUE THREAD

**Issue by bvarwig** [SAP-docs/contribution-guidelines#89]
https://help.sap.com/docs/PRODUCT_ID/contribution-guidelines/content-contribution_sap-terminology.html?state=PRODUCTION&version=1.0&locale=en-US

![image](https://user-images.githubusercontent.com/8438658/232729428-ac1c40ce-6ee4-4e19-b66a-2020f5b84e12.png)

please correct the broken link.

Regards Britta

**Comment by je-hal** [comment]
Thank you @bvarwig for your feedback. I can confirm that the link is broken. We'll look into it and see if we can replace it with a more up-to-date one.

**Comment by je-hal** [comment]
@qmacro : Could you re-publish the contribution guidelines so that we can close this issue? Thanks!

**Comment by bvarwig** [comment]
https://people.sap.com/britta.varwig

**Comment by je-hal** [comment]
Sorry for the delay, the fix is now also done on help.sap.com. Thanks again!

**Comment by qmacro** [comment]
Hi @bvarwig I apologise, the delay was entirely down to me (not @je-hal ).

**Comment by bvarwig** [comment]
shouldn't  we link to the more human-friendly https://www.sapbrandtools.com/naming-center/#/dashboard and its Naming Center at: https://www.sapbrandtools.com/naming-center/#/search/status-search 
Of cause, you need an account, but I assume is ok to request one when you want to contribute. 

But please decide on your own. 

Regards Britta

**Comment by je-hal** [comment]
@bvarwig : Thank you for the idea, but I think that's only available to SAP employees. Recently I saw that now also "Agency Partners" can log in, but for the contribution guidelines, we'd like to refer to something that is public to anyone.

**Comment by bvarwig** [comment]
Hello Je-hal, I agree with your arguments :-)
